CREATE TABLE HEM.CABLE_MODEM_DIM (
   MACADDRESS      STRING,
   MACTYPE         DATE,
   START_DATE      DATE,
   LAST_SEEN       STRING,
   DOCSIS_VERSION  STRING,
   IPTV_FLAG       STRING,
   HDP_INSERT_TS   TIMESTAMP,
   HDP_UPDATE_TS   TIMESTAMP
) STORED AS ORC;
