SET hive.execution.engine=tez;

use cdrdm;

ALTER TABLE CDRDM.FACT_GSM_CDR RENAME TO EXT_CDRDM.FACT_GSM_CDR_QUERYDEV_BKP;

CREATE	TABLE cdrdm.fact_gsm_cdr(
subscriber_no           bigint,
record_sequence_number  bigint,
call_type               smallint,
imsi                    bigint,
imei                    bigint,
exchange_identity       char(15),
switch_identity         char(4),
call_timestamp          string,
chargeable_duration     int,
calling_party_number    varchar(30),
cleansed_calling_number bigint,
called_party_number     varchar(30),
cleansed_called_number  bigint,
original_called_number  varchar(30),
cleansed_original_number        bigint,
reg_seizure_charging_start      int,
mobile_station_roaming_number   bigint,
redirecting_number      varchar(30),
cleansed_redirecting_number     bigint,
fault_code              char(4),
eos_info                bigint,
incoming_route_id       varchar(7),
outgoing_route_id       varchar(7),
first_cell_id           char(14),
last_cell_id            char(14),
charged_party           smallint,
charged_party_number    varchar(30),
cleansed_charged_number bigint,
internal_cause_and_loc  char(5),
traffic_activity_code   varchar(8),
disconnecting_party     int,
partial_output_num      smallint,
rco                     char(2),
ocn                     char(4),
multimediacall          smallint,
teleservicecode         smallint,
tariffclass             smallint,
first_cell_id_extension varchar(4),
subscriptiontype        char(4),
srvccindicator          char(2),
file_name               string,
record_start            bigint,
record_end              bigint,
record_type             string,
family_name             string,
version_id              int,
file_time               string,
file_id                 string,
switch_name             string,
num_records             string,
insert_timestamp        string,
PD_Subscriber_NO	varchar(20),
TR_BAN	bigint,
TR_ACCOUNT_SUB_TYPE	char(1),
TR_COMPANY_CODE	Varchar(15),
TR_FRANCHISE_CD	Varchar(5),
TR_PRODUCT_TYPE	Varchar(1),
TR_BA_ACCOUNT_TYPE	char(1),
Sub_OCN	Varchar(4) ,
Clng_Pty_OCN	Varchar(4),
Cld_Pty_OCN	Varchar(4) ,
Sub_SPID	varchar(4),
Clng_Pty_LRN_SPID	varchar(4),
Cld_Pty_LRN_SPID	Varchar(4),
Dial_Code_Clng_Cld	Varchar(30),
Cnt_name_Clng_Cld	Varchar(150)
)	
PARTITIONED	BY(	
call_timestamp_date	string)
stored as orc TBLPROPERTIES ('orc.compress'='SNAPPY');	



ALTER TABLE CDRDM.FACT_GSM_TRANSIT_CDR RENAME TO EXT_CDRDM.FACT_GSM_TRANSIT_CDR_QUERYDEV_BKP;

CREATE TABLE cdrdm.fact_gsm_transit_cdr(
record_sequence_number  bigint,
imsi                    bigint,
exchange_identity       char(15),
switch_identity         char(4),
call_timestamp          string,
chargeable_duration     int,
calling_party_number    varchar(30),
cleansed_calling_number bigint,
called_party_number     varchar(30),
cleansed_called_number  bigint,
original_called_number  varchar(30),
cleansed_original_number        bigint,
reg_seizure_charging_start      int,
redirecting_number      varchar(30),
cleansed_redirecting_number     bigint,
fault_code              char(4),
eos_info                bigint,
incoming_route_id       varchar(7),
outgoing_route_id       varchar(7),
charged_party           smallint,
charged_party_number    varchar(30),
cleansed_charged_number bigint,
internal_cause_and_loc  char(5),
traffic_activity_code   char(8),
disconnecting_party     smallint,
subscriptiontype        char(4),
file_name               string,
record_start            bigint,
record_end              bigint,
record_type             string,
family_name             string,
version_id              int,
file_time               string,
file_id                 string,
switch_name             string,
num_records             string,
insert_timestamp        string,
Clng_Pty_OCN	Varchar(4) ,
Cld_Pty_OCN	varchar(4),
Clng_Pty_LRN_SPID	varchar(4),
Cld_Pty_LRN_SPID	Varchar(4)
)
PARTITIONED BY (
  call_timestamp_date string)
stored as orc TBLPROPERTIES ('orc.compress'='SNAPPY');


use cdrdm;
drop view if exists vw_Fact_SMS_CDR;

CREATE view `vw_Fact_SMS_CDR` as
select
subscriber_no,
event_record_id,
spid,
orig_msc,
other_msisdn,
orig_msc_zone_indicator,
rate,
charged_party,
action,
rule,
transaction_id,
charge_result,
balance,
rate_plan,
on_net,
originating_service_grade,
terminating_service_grade,
sequence_number,
cast(local_subscriber_timestamp AS varchar(28)) AS local_subscriber_timestamp,
imsi,
ban,
language,
bill_cycle_date,
originating_subscriber_loc,
terminating_subscriber_loc,
rating_rule_description_1,
rating_rule_description_2,
origination_eq_type,
destination_eq_type,
cast(date_1 AS varchar(28)) AS date_1,
ocn,
other_msisdn_sc,
tr_type_omsc,
tr_omsc_plmn,
tr_lac_tac,
tr_ecid_clid,
tr_msc_type,
tr_dcode_country,
tr_account_sub_type,
tr_company_code,
tr_franchise_cd,
tr_ba_account_type,
mtype,
cast(file_name AS varchar(70)) AS file_name,
record_start,
record_end,
cast(record_type AS varchar(28)) AS record_type,
cast(family_name AS varchar(28)) AS family_name,
version_id,
cast(file_time AS varchar(28)) AS file_time,
cast(file_id AS varchar(28)) AS file_id,
cast(switch_name AS varchar(28)) AS switch_name,
cast(num_records AS varchar(28)) AS num_records,
cast(insert_timestamp AS varchar(28)) AS insert_timestamp,
cast(local_subscriber_date AS varchar(28)) AS local_subscriber_date
from cdrdm.Fact_SMS_CDR;

drop view if exists vw_Fact_GSM_CDR;

CREATE view `vw_Fact_GSM_CDR` as
select
subscriber_no,
record_sequence_number,
call_type,
imsi,
imei,
exchange_identity,
switch_identity,
cast(call_timestamp AS varchar(28)) AS call_timestamp,
chargeable_duration,
calling_party_number,
cleansed_calling_number,
called_party_number,
cleansed_called_number,
original_called_number,
cleansed_original_number,
reg_seizure_charging_start,
mobile_station_roaming_number,
redirecting_number,
cleansed_redirecting_number,
fault_code,
eos_info,
incoming_route_id,
outgoing_route_id,
first_cell_id,
last_cell_id,
charged_party,
charged_party_number,
cleansed_charged_number,
internal_cause_and_loc,
traffic_activity_code,
disconnecting_party,
partial_output_num,
rco,
ocn,
multimediacall,
teleservicecode,
tariffclass,
first_cell_id_extension,
subscriptiontype,
srvccindicator,
cast(file_name AS varchar(70)) AS file_name,
record_start,
record_end,
cast(record_type AS varchar(28)) AS record_type,
cast(family_name AS varchar(28)) AS family_name,
version_id,
cast(file_time AS varchar(28)) AS file_time,
cast(file_id AS varchar(28)) AS file_id,
cast(switch_name AS varchar(28)) AS switch_name,
cast(num_records AS varchar(28)) AS num_records,
cast(insert_timestamp AS varchar(28)) AS insert_timestamp,
cast(call_timestamp_date AS varchar(28)) AS call_timestamp_date
from cdrdm.fact_gsm_cdr;

drop view if exists vw_FACT_GPRS_CDR;

CREATE view cdrdm.vw_fact_gprs_cdr as
select 
subscriber_no,
subscriber_no_char,
record_sequence_number,
gprs_choice_mask_archive,
served_imsi,
cast(record_opening_time AS varchar(28)) AS record_opening_time,
served_msisdn,
data_volume_uplink_archive,
data_volume_downlink_archive,
routing_area,
location_area_code,
access_point_name,
reporting_centre_id,
destination_url,
spid,
service_class_group,
content_delivered,
event_protocol_type,
wireless_generation,
event_count,
domain_1,
cdr_type_ind,
served_imei,
sgsn_address,
served_pdp_address,
plmn_id,
duration,
charging_id,
cell_id,
customer_type,
monum,
tracking_area_code,
eutran_cellid,
rec_opening_dt_offset,
cast(file_name AS varchar(70)) AS file_name,
record_start,
record_end,
cast(record_type AS varchar(28)) AS record_type,
cast(family_name AS varchar(70)) AS family_name,
version_id,
cast(file_time AS varchar(28)) AS file_time,
cast(file_id AS varchar(28)) AS file_id,
cast(switch_name AS varchar(28)) AS switch_name,
cast(num_records AS varchar(28)) AS num_records,
cast(insert_timestamp AS varchar(28)) AS insert_timestamp,
cast(record_opening_date AS varchar(28)) AS record_opening_date
from cdrdm.fact_gprs_Cdr;
