--[Version History]
--0.1 _ danchang _ 4/13/2016 _ initial version
--
SET hive.variable.substitute=true;
SET hive.auto.convert.join=true;
SET hive.default.fileformat=textfile;
SET hive.execution.engine=tez;
SET hive.vectorized.execution.enabled=false;
SET hive.vectorized.execution.reduce.enabled=false;
SET hive.cbo.enable=true;
SET hive.compute.query.using.stats=true;
SET hive.stats.fetch.column.stats=true;
SET hive.stats.fetch.partition.stats=true;
SET hive.optimize.index.filter=false;
SET hive.optimize.constant.propagation=false;
SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.tez.auto.reducer.parallelism=true;
SET hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager;
SET hive.exec.orc.default.buffer.size=32768;
SET hive.optimize.sort.dynamic.partition=true;
SET hive.vectorized.execution.reduce.groupby.enabled=false;

use cdrdm;

--ALTER TABLE cdrdm.ucc1205 ADD COLUMNS (networkcalltype STRING, carrieridcode STRING);
--ALTER TABLE cdrdm.ucc1205drop ADD COLUMNS (networkcalltype STRING, carrieridcode STRING);

--rename existing ucc1205ascii table so that its data can be migrated to new table
--ALTER TABLE cdrdm.ucc1205ascii RENAME TO ucc1205ascii_bak;

CREATE TABLE cdrdm.ucc1205ascii( 
file_name STRING,
record_start BIGINT,
record_end BIGINT,
record_type STRING,
family_name STRING,
version_id INT,
file_time STRING,
file_id STRING,
switch_name STRING,
num_records STRING,
recordtype STRING, 
retransmission STRING, 
sip_method STRING, 
role_of_node STRING, 
nodeaddress STRING, 
session_id STRING, 
calling_party_address STRING, 
called_party_address STRING, 
servicerequesttimestamp STRING, 
servicedeliverystarttimestamp STRING, 
servicedeliveryendtimestamp STRING, 
recordopeningtime STRING, 
recordclosuretime STRING, 
servicerequesttimestampnormalized STRING, 
servicedeliverystarttimestampnormalized STRING, 
servicedeliveryendtimestampnormalized STRING, 
chargeableduration STRING, 
timefromsiprequesttostartofcharging STRING, 
interoperatoridentifiers STRING, 
localrecordsequencenumber STRING, 
partialoutputrecordnumber STRING, 
causeforrecordclosing STRING, 
incomplete_cdr_indication STRING, 
ims_charging_identifier STRING, 
list_of_sdp_media_components STRING, 
list_of_normalized_media_components1 STRING, 
list_of_normalized_media_components2 STRING, 
list_of_normalized_media_components3 STRING, 
list_of_normalized_media_components4 STRING, 
list_of_normalized_media_components5 STRING, 
list_of_normalized_media_components6 STRING, 
list_of_normalized_media_components7 STRING, 
list_of_normalized_media_components8 STRING, 
list_of_normalized_media_components9 STRING, 
list_of_normalized_media_components10 STRING, 
list_of_normalized_media_components11 STRING, 
list_of_normalized_media_components12 STRING, 
list_of_normalized_media_components13 STRING, 
list_of_normalized_media_components14 STRING, 
list_of_normalized_media_components15 STRING, 
list_of_normalized_media_components16 STRING, 
list_of_normalized_media_components17 STRING, 
list_of_normalized_media_components18 STRING, 
list_of_normalized_media_components19 STRING, 
list_of_normalized_media_components20 STRING, 
list_of_normalized_media_components21 STRING, 
list_of_normalized_media_components22 STRING, 
list_of_normalized_media_components23 STRING, 
list_of_normalized_media_components24 STRING, 
list_of_normalized_media_components25 STRING, 
list_of_normalized_media_components26 STRING, 
list_of_normalized_media_components27 STRING, 
list_of_normalized_media_components28 STRING, 
list_of_normalized_media_components29 STRING, 
list_of_normalized_media_components30 STRING, 
list_of_normalized_media_components31 STRING, 
list_of_normalized_media_components32 STRING, 
list_of_normalized_media_components33 STRING, 
list_of_normalized_media_components34 STRING, 
list_of_normalized_media_components35 STRING, 
list_of_normalized_media_components36 STRING, 
list_of_normalized_media_components37 STRING, 
list_of_normalized_media_components38 STRING, 
list_of_normalized_media_components39 STRING, 
list_of_normalized_media_components40 STRING, 
list_of_normalized_media_components41 STRING, 
list_of_normalized_media_components42 STRING, 
list_of_normalized_media_components43 STRING, 
list_of_normalized_media_components44 STRING, 
list_of_normalized_media_components45 STRING, 
list_of_normalized_media_components46 STRING, 
list_of_normalized_media_components47 STRING, 
list_of_normalized_media_components48 STRING, 
list_of_normalized_media_components49 STRING, 
list_of_normalized_media_components50 STRING, 
ggsnaddress STRING, 
servicereasonreturncode STRING, 
list_of_message_bodies STRING, 
recordextension STRING, 
expires STRING, 
event STRING, 
listofaccessnetworkinformation1 STRING, 
listofaccessnetworkinformation2 STRING, 
listofaccessnetworkinformation3 STRING, 
listofaccessnetworkinformation4 STRING, 
listofaccessnetworkinformation5 STRING, 
listofaccessnetworkinformation6 STRING, 
listofaccessnetworkinformation7 STRING, 
listofaccessnetworkinformation8 STRING, 
listofaccessnetworkinformation9 STRING, 
listofaccessnetworkinformation10 STRING, 
servicecontextid STRING, 
list_of_subscription_id1 STRING, 
list_of_subscription_id2 STRING, 
list_of_subscription_id3 STRING, 
list_of_subscription_id4 STRING, 
list_of_subscription_id5 STRING, 
list_of_subscription_id6 STRING, 
list_of_subscription_id7 STRING, 
list_of_subscription_id8 STRING, 
list_of_subscription_id9 STRING, 
list_of_subscription_id10 STRING, 
list_of_subscription_id11 STRING, 
list_of_subscription_id12 STRING, 
list_of_early_sdp_media_components STRING, 
imscommunicationserviceidentifier STRING, 
numberportabilityrouting STRING, 
carrierselectrouting STRING, 
sessionpriority STRING, 
requested_party_address STRING, 
list_of_called_asserted_identity STRING, 
mmtelinformation_analyzed_call_type STRING, 
mmtelinformation_called_asserted_identity_presentation_status STRING, 
mmtelinformation_calling_party_address_presentation_status STRING, 
mmtelinformation_conference_id STRING, 
mmtelinformation_dial_around_indicator STRING, 
mmtelinformation_related_icid STRING, 
mmtelinformation_supplementary_service_information1 STRING, 
mmtelinformation_supplementary_service_information2 STRING, 
mmtelinformation_supplementary_service_information3 STRING, 
mmtelinformation_supplementary_service_information4 STRING, 
mmtelinformation_supplementary_service_information5 STRING, 
mmtelinformation_supplementary_service_information6 STRING, 
mmtelinformation_supplementary_service_information7 STRING, 
mmtelinformation_supplementary_service_information8 STRING, 
mmtelinformation_supplementary_service_information9 STRING, 
mmtelinformation_supplementary_service_information10 STRING, 
mobilestationroamingnumber STRING, 
teleservicecode STRING, 
tariffclass STRING, 
pvisitednetworkid STRING, 
networkcalltype STRING, 
carrieridcode STRING 
)
PARTITIONED BY (file_date STRING)
STORED AS ORC
TBLPROPERTIES ("orc.compress"="SNAPPY");

ALTER TABLE cdrdm.ucc1205ascii SET SERDEPROPERTIES ('serialization.encoding'='UTF-8');

--migrate the ucc1205ascii data
INSERT OVERWRITE TABLE cdrdm.ucc1205ascii PARTITION (file_date)
SELECT
file_name,
record_start,
record_end,
record_type,
family_name,
version_id,
file_time,
file_id,
switch_name,
num_records,
recordtype, 
retransmission, 
sip_method, 
role_of_node, 
nodeaddress, 
session_id, 
calling_party_address, 
called_party_address, 
servicerequesttimestamp, 
servicedeliverystarttimestamp, 
servicedeliveryendtimestamp, 
recordopeningtime, 
recordclosuretime, 
servicerequesttimestampnormalized, 
servicedeliverystarttimestampnormalized, 
servicedeliveryendtimestampnormalized, 
chargeableduration, 
timefromsiprequesttostartofcharging, 
interoperatoridentifiers, 
localrecordsequencenumber, 
partialoutputrecordnumber, 
causeforrecordclosing, 
incomplete_cdr_indication, 
ims_charging_identifier, 
list_of_sdp_media_components, 
list_of_normalized_media_components1, 
list_of_normalized_media_components2, 
list_of_normalized_media_components3, 
list_of_normalized_media_components4, 
list_of_normalized_media_components5, 
list_of_normalized_media_components6, 
list_of_normalized_media_components7, 
list_of_normalized_media_components8, 
list_of_normalized_media_components9, 
list_of_normalized_media_components10, 
list_of_normalized_media_components11, 
list_of_normalized_media_components12, 
list_of_normalized_media_components13, 
list_of_normalized_media_components14, 
list_of_normalized_media_components15, 
list_of_normalized_media_components16, 
list_of_normalized_media_components17, 
list_of_normalized_media_components18, 
list_of_normalized_media_components19, 
list_of_normalized_media_components20, 
list_of_normalized_media_components21, 
list_of_normalized_media_components22, 
list_of_normalized_media_components23, 
list_of_normalized_media_components24, 
list_of_normalized_media_components25, 
list_of_normalized_media_components26, 
list_of_normalized_media_components27, 
list_of_normalized_media_components28, 
list_of_normalized_media_components29, 
list_of_normalized_media_components30, 
list_of_normalized_media_components31, 
list_of_normalized_media_components32, 
list_of_normalized_media_components33, 
list_of_normalized_media_components34, 
list_of_normalized_media_components35, 
list_of_normalized_media_components36, 
list_of_normalized_media_components37, 
list_of_normalized_media_components38, 
list_of_normalized_media_components39, 
list_of_normalized_media_components40, 
list_of_normalized_media_components41, 
list_of_normalized_media_components42, 
list_of_normalized_media_components43, 
list_of_normalized_media_components44, 
list_of_normalized_media_components45, 
list_of_normalized_media_components46, 
list_of_normalized_media_components47, 
list_of_normalized_media_components48, 
list_of_normalized_media_components49, 
list_of_normalized_media_components50, 
ggsnaddress, 
servicereasonreturncode, 
list_of_message_bodies, 
recordextension, 
expires, 
event, 
listofaccessnetworkinformation1, 
listofaccessnetworkinformation2, 
listofaccessnetworkinformation3, 
listofaccessnetworkinformation4, 
listofaccessnetworkinformation5, 
listofaccessnetworkinformation6, 
listofaccessnetworkinformation7, 
listofaccessnetworkinformation8, 
listofaccessnetworkinformation9, 
listofaccessnetworkinformation10, 
servicecontextid, 
list_of_subscription_id1, 
list_of_subscription_id2, 
list_of_subscription_id3, 
list_of_subscription_id4, 
list_of_subscription_id5, 
list_of_subscription_id6, 
list_of_subscription_id7, 
list_of_subscription_id8, 
list_of_subscription_id9, 
list_of_subscription_id10, 
list_of_subscription_id11, 
NULL AS list_of_subscription_id12, 
list_of_early_sdp_media_components, 
imscommunicationserviceidentifier, 
numberportabilityrouting, 
carrierselectrouting, 
sessionpriority, 
requested_party_address, 
list_of_called_asserted_identity, 
mmtelinformation_analyzed_call_type, 
mmtelinformation_called_asserted_identity_presentation_status, 
mmtelinformation_calling_party_address_presentation_status, 
mmtelinformation_conference_id, 
mmtelinformation_dial_around_indicator, 
mmtelinformation_related_icid, 
mmtelinformation_supplementary_service_information1, 
mmtelinformation_supplementary_service_information2, 
mmtelinformation_supplementary_service_information3, 
mmtelinformation_supplementary_service_information4, 
mmtelinformation_supplementary_service_information5, 
mmtelinformation_supplementary_service_information6, 
mmtelinformation_supplementary_service_information7, 
mmtelinformation_supplementary_service_information8, 
mmtelinformation_supplementary_service_information9, 
mmtelinformation_supplementary_service_information10, 
mobilestationroamingnumber, 
teleservicecode, 
tariffclass, 
pvisitednetworkid, 
NULL AS networkcalltype, 
NULL AS carrieridcode,
file_date 
FROM cdrdm.ucc1205ascii_bak;



