DROP TABLE IF EXISTS DATA_PODS.DIM_WL_HUPFREQ_SUB_DLY PURGE;
CREATE TABLE IF NOT EXISTS DATA_PODS.DIM_WL_HUPFREQ_SUB_DLY       
(       
BRAND STRING,
HUP_REQUEST_DATE  DATE,
CTN_SUB_LINES INT,
TOTAL_HUP_IN_YEAR INT,
HUP_PERCENT DOUBLE,
HUP_PERCENT_CUMSUM DOUBLE,
DECILE	DOUBLE,
HDP_UPDATE_TS TIMESTAMP
)
PARTITIONED BY
(HUP_YEAR INT,
HUP_MONTH INT
)
TBLPROPERTIES ("ORC.COMPRESS"="SNAPPY");

