CREATE TABLE IF NOT EXISTS DATA_PODS.DIM_WL_IFRSLEGACY_SUB_WKLY
(
BAN BIGINT,
SUBSCRIBER_NO VARCHAR(20),
LST_FRANCHISE_TP VARCHAR(1),
DD_IND VARCHAR(3),
FN_CREDIT_AMT DOUBLE,
SERV_REV_DRAWDOWN DOUBLE,
IAS_POST DOUBLE,
IFRS_DD DOUBLE, 
IFRS_REV DOUBLE,
EOC_IND TINYINT,
EOC_DD DOUBLE,
HDP_UPDATE_TS  TIMESTAMP
)
PARTITIONED BY
(
CALENDAR_YEAR INT,
CALENDAR_MONTH INT
)
TBLPROPERTIES("ORC.COMPRESS"="SNAPPY");
                                  
