DROP TABLE IF EXISTS DATA_PODS.DIM_WL_PPCFREQ_SUB_DLY PURGE;
CREATE TABLE IF NOT EXISTS DATA_PODS.DIM_WL_PPCFREQ_SUB_DLY
(       
BRAND STRING,
PPC_EFF_DATE  DATE,
CTN_SUB_LINES INT,
TOTAL_PPC_IN_YEAR INT,
PPC_PERCENT DOUBLE,
PPC_PERCENT_CUMSUM DOUBLE,
DECILE	DOUBLE,
HDP_UPDATE_TS TIMESTAMP
)
PARTITIONED BY 
(PPC_YEAR INT,
PPC_MONTH INT)
TBLPROPERTIES ("ORC.COMPRESS"="SNAPPY");

