ALTER TABLE ELA_V21.SERVICE_AGREEMENT CHANGE TRX_ID TRX_ID DECIMAL(12,0);
ALTER TABLE ELA_V21.SERVICE_AGREEMENT CHANGE INS_TRX_ID INS_TRX_ID DECIMAL(12,0);

ALTER TABLE EXT_ELA_V21.SERVICE_AGREEMENT__PREV CHANGE TRX_ID TRX_ID DECIMAL(12,0);
ALTER TABLE EXT_ELA_V21.SERVICE_AGREEMENT__PREV CHANGE INS_TRX_ID INS_TRX_ID DECIMAL(12,0);

ALTER TABLE EXT_ELA_V21.SERVICE_AGREEMENT__SQOOP_IMPORT CHANGE TRX_ID TRX_ID DECIMAL(12,0);
ALTER TABLE EXT_ELA_V21.SERVICE_AGREEMENT__SQOOP_IMPORT CHANGE INS_TRX_ID INS_TRX_ID DECIMAL(12,0);

