
create table stb_viewership.rpt_descriptor_ref (
DESCRIPTOR_ID VARCHAR(7),
TCODE CHAR(1),
DSC VARCHAR(125),
TEXT VARCHAR(8000),
SOURCE_FILENAME  VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP)
STORED AS ORC;
