header.uuid,
null as versionNum,
cast(header.`timestamp` as Timestamp),
device.partner,
header.hostname,
null as name,
device.receiverId,
device.deviceId,
device.deviceSourceID,
device.account,
device.accountSourceID,
device.macAddress,
device.ecmMacAddress,
device.firmwareVersion,
cast(eventTimestamp as Timestamp),
reasonCode,
application,
event_date,
hdp_create_ts,
hdp_update_ts
