create table ext_stb_viewership.rpt_program_keywords_sqp_imp_merge
(
PROGRAM_ID BIGINT,
KEYWORD_ID VARCHAR(7),
WEIGHT BIGINT,
DELTA_IND VARCHAR(3),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
STORED AS ORC;

