create  table  stb_viewership.hist_rpt_keywords_ref(
KEYWORD_ID VARCHAR(10),
DESCRIPTION VARCHAR(60),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
PARTITIONED BY(SQOOP_EXT_DATE DATE)
stored as ORC;
