

create  table  stb_viewership.hist_rpt_descriptor_ref(
DESCRIPTOR_ID VARCHAR(7),
TCODE CHAR(1),
DSC VARCHAR(125),
TEXT VARCHAR(8000),
SOURCE_FILENAME  VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
PARTITIONED BY(SQOOP_EXT_DATE DATE)
stored as ORC
