create  table  stb_viewership.hist_rpt_station(
CHANNEL_ID_NUMBER BIGINT,
CALL_LETTER VARCHAR(50),
EXPANDED_CALL_LETTER VARCHAR(50),
TMZNE VARCHAR(3),
TIME_ZONE_CHANGE CHAR(1),
CITY VARCHAR(40),
STATE VARCHAR(50),
WEBSITE_ADDRESS VARCHAR(254),
NETWORK VARCHAR(10),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
PARTITIONED BY(SQOOP_EXT_DATE DATE)
stored as ORC;
