SUB_SYSTEM,     
SOURCE,         
KPI_ID,         
KPI_DESC,       
KPI_COLUMN,     
BUSINESS_DATE,  
KPI_COUNT,      
TOTAL_REC_COUNT,
STATUS,         
CREATION_TS,    
UPDATE_TS,      
VALIDATION_TYPE,
cast(cast(CREATION_TS as Timestamp) as DATE) as Event_Date
