create table ext_stb_viewership.hist_rpt_program_genres_sqp_imp
(
PROGRAM_ID BIGINT,
GENRE VARCHAR(60),
GENRE_SEQUENCE BIGINT,
DELTA_IND VARCHAR(3),
PROGRAM_GENRE_ID BIGINT,
GENRE_ID BIGINT,
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
STORED AS ORC;
