create  table  stb_viewership.hist_rpt_descriptor_all_language_ref(
DESCRIPTOR_ID VARCHAR(7),
LANGUAGE_ID VARCHAR(2),
TCODE CHAR(1),
DSC VARCHAR(125),
TEXT VARCHAR(8000),
DELTA_IND VARCHAR(3),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
PARTITIONED BY(SQOOP_EXT_DATE DATE)
stored as ORC;
