CREATE TABLE IPTV.AUDIT_DATAQUALITY
(
SOURCE           VARCHAR(30),  
SUB_SYSTEM       VARCHAR(50), 
KPI_ID           BIGINT,    
KPI_DESC         VARCHAR(200), 
KPI_COLUMN       VARCHAR(50),  
BUSINESS_DATE    TIMESTAMP,          
KPI_COUNT        BIGINT,    
TOTAL_REC_COUNT  BIGINT,   
STATUS           VARCHAR(15),  
CREATION_TS      TIMESTAMP,  
UPDATE_TS        TIMESTAMP,  
VALIDATION_TYPE  VARCHAR(50),
EVENT_DATE       DATE    
)
stored as ORC;
