create  table  stb_viewership.hist_rpt_program_keywords(
PROGRAM_ID BIGINT,
KEYWORD_ID VARCHAR(7),
WEIGHT BIGINT,
DELTA_IND VARCHAR(3),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP
)
PARTITIONED BY(SQOOP_EXT_DATE DATE)
stored as ORC;
