create table ext_stb_viewership.rpt_station_sqp_imp_merge (
CHANNEL_ID_NUMBER BIGINT,
CALL_LETTER VARCHAR(50),
EXPANDED_CALL_LETTER VARCHAR(50),
TMZNE VARCHAR(3),
TIME_ZONE_CHANGE CHAR(1),
CITY VARCHAR(40),
STATE VARCHAR(50),
WEBSITE_ADDRESS VARCHAR(254),
NETWORK VARCHAR(10),
SOURCE_FILENAME VARCHAR(100),
DATALAKE_LOAD_TS TIMESTAMP)
STORED AS ORC;
