CREATE TABLE HEM.RHSI_MODEM_MODEL_DIM(
   MODEM_MAKE       STRING,
   MODEM_MODEL      STRING,
   TECHNOLOGY       STRING,
   DS_TUNERS_COUNT  INT,
   US_TUNERS_COUNT  INT,
   HDP_INSERT_TS    TIMESTAMP,
   HDP_UPDATE_TS    TIMESTAMP
)STORED AS ORC
