drop table if exists HEM.SUBSCRIBER_MODEM_DIM_MVW_STAGE;
CREATE TABLE HEM.SUBSCRIBER_MODEM_DIM_MVW_STAGE as SELECT * FROM HEM.SUBSCRIBER_MODEM_DIM_VW;
drop table if exists HEM.SUBSCRIBER_MODEM_DIM_MVW;
alter table HEM.SUBSCRIBER_MODEM_DIM_MVW_STAGE rename to HEM.SUBSCRIBER_MODEM_DIM_MVW;
