CREATE TABLE HEM.DS_OFDM_CHANNEL_CONFIG(
CMTS_HOST_NAME        STRING,
MAC_DOMAIN            STRING,
NODE                  STRING,
CHANNEL_COUNT         INT,
CHANNEL_MODULATION    STRING,
CAPACITY_MBPS         DOUBLE,
REPORT_DATE           DATE,
HDP_INSERT_TS         TIMESTAMP,
HDP_UPDATE_TS         TIMESTAMP
)
STORED AS ORC;
