CREATE TABLE IF NOT EXISTS HEM.PRODUCT_TIER_REFERENCE(
   PRODUCT_CODE          STRING,
   TIER                  STRING,
   TIER_TYPE             STRING,
   TIER_DETAILS          STRING,
   OVERAGE_THRESHOLD_GB  INT,
   SERVICE_CLASS         STRING,
   DOWNLOAD_SPEED_KBPS   BIGINT,
   UPLOAD_SPEED_KBPS     BIGINT,
   HDP_INSERT_TS    TIMESTAMP,
   HDP_UPDATE_TS    TIMESTAMP
)ROW FORMAT DELIMITED
   STORED AS ORC
