CREATE TABLE IPTV.HSHLD_LOCATION_XREF (
   HHID STRING,
   SUB_STATUS STRING,
   INSTANCE_NAME STRING,
   INSTALL_DT TIMESTAMP,
   SERVICE_END_DT TIMESTAMP,
   STATUS_DT TIMESTAMP,
   SUBSCRIBER_TYPE STRING,
   PROVINCE STRING,
   CITY STRING,
   COUNTRY STRING,
   ZIPCODE STRING,
   X_ADDRESS_ID STRING,
   ETL_INSERT_TS TIMESTAMP
) 
STORED AS ORC;
