CREATE TABLE IPTV.ENT_VIEWERSHIP_METADATA_REF (
FEED_TYPE          STRING,
METADATA_TYPE      STRING,
METADATA_VALUE     STRING,
BUSINESS_CONTEXT   STRING,
CONTEXT_ATTRIBUTE  STRING,
ETL_INSRT_DT       TIMESTAMP,
ETL_UPDT_DT        TIMESTAMP,
HDP_CREATE_TS      TIMESTAMP,
HDP_UPDATE_TS      TIMESTAMP
)STORED AS ORC
;
