INSERT OVERWRITE TABLE IPTV.HSHLD_LOCATION_XREF
SELECT DISTINCT 
   S.SUBSCRIBER_SEQ_NBR HHID,
   S.SUB_STATUS,
   S.INSTANCE_NAME,
   S.INSTALL_DT,
   S.SERVICE_END_DT,
   S.STATUS_DT,
   S.SUBSCRIBER_TYPE,
   A.PROVINCE,
   A.CITY,
   A.COUNTRY,
   A.ZIPCODE,
   A.X_ADDRESS_ID,
   from_unixtime(unix_timestamp()) AS ETL_INSERT_TS
FROM app_maestro.sbscrbrdim S
LEFT JOIN app_maestro.addrdim A
ON A.ADDRESS_KEY = S.ADDRESS_KEY
WHERE A.CRNT_F='Y' AND S.CRNT_F='Y'
AND S.INSTANCE_NAME='IPTV';

