INSERT INTO HEM.CM_THROUGHPUT_STG PARTITION(EVENT_DATE_UTC)
SELECT * FROM HEM.CM_THROUGHPUT_STG_1 WHERE EVENT_DATE_UTC = '${hiveconf:dt}'
AND CM_MAC_ADDR NOT IN (SELECT CM_MAC_ADDR FROM  HEM.CM_THROUGHPUT_STG WHERE  EVENT_DATE_UTC = '${hiveconf:dt}');






