create table DATA_PODS.WL_PROFILE_ACCT_SUMMARY_DLY_BKP AS select * from DATA_PODS.WL_PROFILE_ACCT_SUMMARY_DLY;

ALTER TABLE DATA_PODS.WL_PROFILE_ACCT_SUMMARY_DLY ADD columns (consolidated_ind varchar(1)) CASCADE;

desc DATA_PODS.WL_PROFILE_ACCT_SUMMARY_DLY;
